### Setup
@base_url = http://localhost:8000/api/v1

### Login
# @name login
POST {{base_url}}/auth/login/
Content-Type: application/json

{
    "email": "camoakohene84@gmail.com",
    "password": "kriswale"
}
### Get Access Token
@access_token = {{login.response.body.access}}

### Create User
GET {{base_url}}/users/
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Create Product
PUT  {{base_url}}/product-categories/1/
Content-Type: application/json

{
    "name": "Product Category 1",
    "description": "Product Category 1 description",
}

### Create Production Batch
POST {{base_url}}/production-batches/
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "shop": 1,
  "product": 3,
  "quantity_produced": 120,
  "ingredients": [
    { "ingredient": 1, "quantity_used": 1 }
  ]
}