# Generated by Django 6.0.1 on 2026-03-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
