# Generated by Django 6.0.1 on 2026-03-25 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_pendingpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingpayment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_payments', to='orders.order'),
        ),
    ]
